sudo: false
language: go
go:
  - 1.7
before_install:
  - go get -t -v ./...
  - go get github.com/modocache/gover
  - go get github.com/mattn/goveralls
  - bash build_etcd.sh
script:
  - go test -coverprofile=vault.coverprofile ./vault
  - go test -coverprofile=etcd.coverprofile ./etcd
  - gover
  - goveralls -coverprofile=gover.coverprofile -service=travis-ci
