sudo: false
language: go
go:
- 1.7
before_install:
- bash build_etcd.sh
- go get -t -v ./...
- cd $GOPATH/src/github.com/hashicorp/vault && git checkout v0.6.4 && cd -
install:
- go get github.com/haya14busa/reviewdog/cmd/reviewdog
- go get github.com/modocache/gover
- go get github.com/mattn/goveralls
script:
- go test -coverprofile=vault.coverprofile ./vault
- go test -coverprofile=etcd.coverprofile ./etcd
- gover
- goveralls -coverprofile=gover.coverprofile -service=travis-ci
- >-
  golint ./... | reviewdog -f=golint -ci=travi
env:
  global:
  - secure: REKEwn+EhfyCS8FMym+pO/J1Ue+r3NgvoV7DUlCnDSRM27K/wpDmljkC4N2JVIwjpirggOMUBP3Izslbtfj1YlNwYotx3OjFdBnqphMbVlwZibxj7xjVM/4zn8eT/MxK+yDrvmCa3ReDrmgPqBS5yTeGks11of3rXGkq4MW73ddr1IPgPg9yguO9T8DGpPUFp8H/q36+qr/ekHXStRj0OcD8u4ZtPluU9yi46r3+NSNdDCxNhjGZToH9Ug6JhmT2fmnxWR/2/muLAguyHto5Qzg9r6EKu1Ha2+xkDeTm4zIcfEU5J+Ip2gQ52FBWCtwALJnCMdz4wyI/ZLSR6QsIcFNW+jEHWw4iK+D5mqM6wgc5jweUtkCom/bS5JSAGtSUMcMO369o4K2T+UwClw8TnfVaadW4tbCStlvNRp/kRxSrikIygzMG85rnIAtfwDLUdw0/cMhUDExVYEO4NJINxaysytxt0kXA+z454EfiwJvaJ3+SPEpUJwQzzVNeUcTVwsRIUjYRh1n41m7n1m9BteHxpHGihbXY4T17xE1PjvYkOH44ol2Ib10k8EMMRd5mKwz8Q1brGn1vxs664209h3VQ9sISCo7mrNzgJNxgML6/Hq4c7JtYXQ3r1LQqsmLGsDKQGACUip3df/VeNOMZMBb41LHHyVp1B4q/4zdTKGc=
  - secure: fU2FBipgaIp/tD3uR/TzhspGlLDnk+Oe5/G5zbpoU9sejNhAmO0dYzQtmrtlIXlBZEx2HnO1qZaHgxBKIcDR1RSH9BIssGPyA/nQsRyIL196kTNo3LpRjHnbm0/ZcoVlQrLw3JgbW/R2GQAkmqIw317HConE5w8NNvXiD6DHm6myOg2wZTOSY4gq5A6l+R/3haIKO4VtmB+YvRVSwkz+MiJhgD+j9ROxQCzhGmCrWZMRH74D/5NiLtjpLU/E9JWnYPC0gwszvtOYQdLT9EEO5yX2jI0G0sYNQa964DjP38bFSd2W1RNmGz3KbgT+UPoodZdXTM7nSgwZ4rAuAxxnaS6HV7JvaiTMN4w6+5q4NV/ZcM96eTmAQf5cJ3T0ON5H+180VY/HL3uZ/NxtXrnk7NR9JvqbZrxK27WRpHF2ye6W8kLtc6syvSX8pfBykBGpzHJYv9wmld3wip6hAvF4dWik35XZjJN/sIQVlGKZVokqO+NZc5+iEpKw3bFVxBi0pYaMcP+Drr6lMoPvay1OQahEXUc6d7fWZCMvGGAtul99CNjko36tbfaJpTMMbS/SKke1a3opfDuJYMtnIwiypX2Wr+UZh8evn3bFZuHqi0q9/nFS13mTEoOgth8o2lxAVyfH9FPudP7HDZdM2UU9AsFmuNSYsR89yAuBwq9MTvA=
