sudo: false
language: go
matrix:
  include:
  - go: "1.10.x"
  - go: "1.11.x"

env:
  - GO111MODULE=on

before_install:
  - go get -v -t ./...
  - go get github.com/mattn/goveralls

script:
  - go test -v ./... -coverprofile=coverage.out && go tool cover -func=coverage.out
  - goveralls -coverprofile=coverage.out -service=travis-ci
